name: Bug Report (from Code review)
description: File a bugfix order for Claude
title: "bug: <short title>"
labels: ["type:bug", "agent:claude"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One‑sentence description of the bug.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction / Proof
      description: Steps or failing test/logs.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Blocker
        - Major
        - Minor
    validations:
      required: true
  - type: textarea
    id: suggested
    attributes:
      label: Suggested Fix
      description: Concise guidance for Claude.

