name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (unit tests)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Enforce no-sudo policy in scripts
        run: |
          chmod +x scripts/check_no_sudo.sh
          ./scripts/check_no_sudo.sh

      - name: Run unit tests (with JUnit XML)
        run: |
          mkdir -p reports
          pytest -q --junitxml=reports/junit.xml

      - name: Upload unit test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-xml
          path: reports/junit.xml

      - name: Build images and run in-network smoke
        run: |
          chmod +x scripts/ci_smoke.sh scripts/smoke_in_network.sh
          ./scripts/ci_smoke.sh
